adaptive_concurrency: true
allowed_user_ids:
- me
always_fresh_download: false
batch_interval: 500
batch_size: 20
bot_token: 8479400961:AAHKK-Ke9HO4sXrIM-MuiRyYX75emIuu7os
chat: []
date_format: '%Y_%m'
enable_private_chat: true
file_formats: {}
file_name_prefix:
- message_id
- file_name
file_name_prefix_split: ' - '
file_path_prefix:
- chat_title
group_same_channel_files: true
max_connected_channels: 10
max_download_task: 3
media_types:
- audio
- document
- photo
- video
- voice
- animation
proxy: null
save_path: ./downloads
user_api:
  api_hash: db62a098851588b5fd97bbee6ddd1536
  api_id: '30578955'
  proxy: null
