adaptive_concurrency: true
allowed_user_ids: []
always_fresh_download: false
batch_interval: 500
batch_size: 20
bot_token: ''
chat: []
date_format: '%Y_%m'
enable_private_chat: true
file_formats: {}
file_name_prefix:
  - message_id
  - file_name
file_name_prefix_split: ' - '
file_path_prefix:
  - chat_title
group_same_channel_files: true
max_connected_channels: 10
max_download_task: 3
media_types:
  - audio
  - document
  - photo
  - video
  - voice
  - animation
proxy: null
save_path: ./downloads
web_host: 127.0.0.1
web_port: 8000
web_cors_origins:
  - http://127.0.0.1:8000
environment: local
aliyundrive_upload:
  enabled: false
  remote_path: /video
  delete_after_upload: false
user_api:
  api_hash: ''
  api_id: ''
  proxy: null
